### ISSUE TITLE
TOC would be possible, but there are blocking items

### ISSUE THREAD

**Issue by kappapiana** [OpenChain-Project/Security-Assurance-Specification#10]
Using Markdown and without adding confusing code, one can easily generate a Table of Content.

However, there are two hiccups:

- interpreters are able to provide an ID even if two headlines are identical
   - `# carlo` and  `## carlo ` will receive two different ID's although identical (`carlo-1` and `carlo-2`)
- interpreters will ignore numbers, spaces, dots and other stuff and ignore case, but since they are not identical, headlines with those characters and the same words will get the same ID:
   - `# 1. carlo` and  `# 2. Carlo` will be given the same ID (`<h1 id="carlo">` in HTML).
   - there is no way to point to 2. Carlo;  parser will tell "duplicated id"

The solution would be:

- add an express label, which will be picked up as internal anchor, such as:

```
# example of a title {#manual-anchor}
```
- always use different headlines
- drop the manually added numbering
- not adding a TOC at all.

In the current version the problem arises with only two headlines.

[WARNING] Duplicate identifier 'verification-materials'
[WARNING] Duplicate identifier 'security-assurance'

**Comment by shanecoughlan** [comment]
Will address outside of call, plan to use express labels as flagged.

**Comment by shanecoughlan** [comment]
Decided not to fix here. Will hand over to ISO editor to check his ISO format requirement before getting creative. Carlo, thanks for flagging. It triggered a useful discussion with the result that we *will* fix after ISO editor feedback.
